sonar.projectKey=dktunited_dsi-rt-effimate-client
sonar.organization=dktunited

#sonar.projectVersion=1.0
sonar.exclusions=node_modules/**,build/**,public/**,__mocks__/**,coverage/**,**/dist/**,**/test-config/**,**/interfaces/**,**/jestGlobalMocks.ts,**/*.module.ts,**/*.mock.ts,**/*.json,/src/clients/kafka/**,/src/server.ts,/src/test/**,/src/clients/db/**,/src/dto/**,/src/utils/**,**/*.env,**/migrations/**,**/config/**,/src/helper/**,/src/hooks/**,**/*.ts
# Exclude unnecessary directories
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
# sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.tsx
sonar.test.inclusions=**/*.test.tsx

#sonar.sources=.
#sonar.tests=tests
#sonar.exclusions=tests/**/*,geodb.mmdb
# Encoding of the source code. Default is default system encoding

#sonar.javascript.lcov.reportPaths=./coverage/lcov.info
